#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

RECONFIGURE=false
USE_PREBUILT_IMAGE=false
for arg in "$@"; do
    case "$arg" in
        --reconfigure|--init)
            RECONFIGURE=true
            ;;
        --pull-image)
            USE_PREBUILT_IMAGE=true
            ;;
        -h|--help)
            echo "用法: ./deploy.sh [--reconfigure] [--pull-image]"
            echo "  --reconfigure  重新生成 .env，重新选择数据库和初始管理员"
            echo "  --pull-image    使用 GHCR 预构建镜像部署，不在本机编译"
            exit 0
            ;;
        *)
            echo "未知参数: $arg"
            exit 1
            ;;
    esac
done

if ! command -v docker >/dev/null 2>&1; then
    echo "错误: 未找到 Docker，请先安装 Docker"
    exit 1
fi

if docker compose version >/dev/null 2>&1; then
    COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE=(docker-compose)
else
    echo "错误: 未找到 Docker Compose，请先安装 docker compose 插件"
    exit 1
fi

get_env() {
    local key="$1"
    local fallback="${2:-}"
    local line name value

    if [ -f .env ]; then
        while IFS= read -r line || [ -n "$line" ]; do
            line="${line%%#*}"
            [ -z "$line" ] && continue
            name="${line%%=*}"
            value="${line#*=}"
            name="${name//[[:space:]]/}"
            if [ "$name" = "$key" ]; then
                value="${value%\"}"
                value="${value#\"}"
                value="${value%\'}"
                value="${value#\'}"
                printf '%s\n' "$value"
                return
            fi
        done < .env
    fi

    printf '%s\n' "$fallback"
}

random_password() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | cut -c1-24
    else
        date +%s%N | sha256sum | cut -c1-24
    fi
}

prompt() {
    local label="$1"
    local default_value="$2"
    local value

    read -r -p "$label [$default_value]: " value
    if [ -z "$value" ]; then
        value="$default_value"
    fi
    printf '%s\n' "$value"
}

prompt_password() {
    local value confirm generated
    generated="$(random_password)"

    while true; do
        read -r -s -p "初始管理员密码，留空自动生成: " value
        echo ""
        if [ -z "$value" ]; then
            value="$generated"
            break
        fi
        if [ "${#value}" -lt 6 ]; then
            echo "密码长度至少 6 位"
            continue
        fi
        if [[ "$value" == *[[:space:]#=]* ]]; then
            echo "密码不能包含空格、# 或 =，避免写入 .env 后解析失败"
            continue
        fi
        read -r -s -p "再次输入初始管理员密码: " confirm
        echo ""
        if [ "$value" != "$confirm" ]; then
            echo "两次密码不一致，请重新输入"
            continue
        fi
        break
    done

    printf '%s\n' "$value"
}

write_env() {
    local db_type="$1"
    local app_port="$2"
    local allowed_origins="$3"
    local admin_username="$4"
    local admin_password="$5"
    local admin_email="$6"
    local admin_name="$7"

    local mysql_database="${8:-lab_asset}"
    local mysql_user="${9:-lab_asset}"
    local mysql_password="${10:-}"
    local mysql_root_password="${11:-}"
    local postgres_db="${12:-lab_asset}"
    local postgres_user="${13:-lab_asset}"
    local postgres_password="${14:-}"

    cat > .env <<EOF
# Generated by deploy.sh
APP_PORT=$app_port
TZ=Asia/Shanghai

DB_TYPE=$db_type
ALLOWED_ORIGINS=$allowed_origins

ADMIN_USERNAME=$admin_username
ADMIN_PASSWORD=$admin_password
ADMIN_EMAIL=$admin_email
ADMIN_NAME=$admin_name

# SMTP Email Configuration (optional)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=
SMTP_ENABLED=false
SMTP_SECURE=false
EOF

    if [ "$db_type" = "mysql" ]; then
        cat >> .env <<EOF

# MySQL Configuration
MYSQL_ROOT_PASSWORD=$mysql_root_password
MYSQL_DATABASE=$mysql_database
MYSQL_USER=$mysql_user
MYSQL_PASSWORD=$mysql_password
EOF
    fi

    if [ "$db_type" = "postgres" ]; then
        cat >> .env <<EOF

# PostgreSQL Configuration
POSTGRES_DB=$postgres_db
POSTGRES_USER=$postgres_user
POSTGRES_PASSWORD=$postgres_password
EOF
    fi
}

init_env() {
    if [ ! -t 0 ]; then
        echo "错误: 首次初始化需要交互式终端。请在服务器终端执行 ./deploy.sh"
        exit 1
    fi

    echo "实验室资产管理系统 Docker 初始化"
    echo ""

    local app_port allowed_origins admin_username admin_email admin_name admin_password
    local db_choice db_type
    local mysql_database mysql_user mysql_password mysql_root_password
    local postgres_db postgres_user postgres_password

    app_port="$(prompt "对外访问端口" "8080")"
    allowed_origins="$(prompt "允许访问来源，多个用英文逗号分隔" "http://localhost:$app_port")"

    echo ""
    echo "选择数据库："
    echo "  1) SQLite（推荐，零配置，适合单机部署）"
    echo "  2) MySQL（适合已有 MySQL 运维经验）"
    echo "  3) PostgreSQL（适合已有 PostgreSQL 运维经验）"
    read -r -p "请选择 [1]: " db_choice
    case "${db_choice:-1}" in
        1)
            db_type="sqlite"
            ;;
        2)
            db_type="mysql"
            mysql_database="$(prompt "MySQL 数据库名" "lab_asset")"
            mysql_user="$(prompt "MySQL 用户名" "lab_asset")"
            mysql_password="$(random_password)"
            mysql_root_password="$(random_password)"
            echo "MySQL 密码已自动生成并写入 .env"
            ;;
        3)
            db_type="postgres"
            postgres_db="$(prompt "PostgreSQL 数据库名" "lab_asset")"
            postgres_user="$(prompt "PostgreSQL 用户名" "lab_asset")"
            postgres_password="$(random_password)"
            echo "PostgreSQL 密码已自动生成并写入 .env"
            ;;
        *)
            echo "错误: 无效数据库选项"
            exit 1
            ;;
    esac

    echo ""
    admin_username="$(prompt "初始管理员用户名" "admin")"
    admin_email="$(prompt "初始管理员邮箱" "admin@example.com")"
    admin_name="$(prompt "初始管理员名称" "系统管理员")"
    admin_password="$(prompt_password)"

    write_env \
        "$db_type" \
        "$app_port" \
        "$allowed_origins" \
        "$admin_username" \
        "$admin_password" \
        "$admin_email" \
        "$admin_name" \
        "${mysql_database:-lab_asset}" \
        "${mysql_user:-lab_asset}" \
        "${mysql_password:-}" \
        "${mysql_root_password:-}" \
        "${postgres_db:-lab_asset}" \
        "${postgres_user:-lab_asset}" \
        "${postgres_password:-}"

    chmod 600 .env
    echo ""
    echo "初始化配置已写入 .env"
}

if [ "$RECONFIGURE" = true ] || [ ! -f .env ]; then
    if [ -f .env ] && [ "$RECONFIGURE" = true ]; then
        cp .env ".env.bak.$(date +%Y%m%d_%H%M%S)"
        echo "已备份旧配置文件"
    fi
    init_env
fi

mkdir -p data backups

DB_TYPE_VALUE="$(get_env DB_TYPE sqlite)"
APP_PORT_VALUE="$(get_env APP_PORT 8080)"
ADMIN_USERNAME_VALUE="$(get_env ADMIN_USERNAME admin)"

if [ "$USE_PREBUILT_IMAGE" = true ]; then
    COMPOSE_FILES=(-f docker-compose.release.yml)
else
    COMPOSE_FILES=(-f docker-compose.yml)
fi
case "$DB_TYPE_VALUE" in
    sqlite)
        ;;
    mysql)
        COMPOSE_FILES+=(-f docker-compose.mysql.yml)
        ;;
    postgres|postgresql)
        COMPOSE_FILES+=(-f docker-compose.postgres.yml)
        ;;
    *)
        echo "错误: 不支持的 DB_TYPE: $DB_TYPE_VALUE"
        exit 1
        ;;
esac

echo "开始构建并启动实验室资产管理系统..."
"${COMPOSE[@]}" "${COMPOSE_FILES[@]}" up -d --build

echo ""
echo "部署完成"
if [ "$USE_PREBUILT_IMAGE" = true ]; then
    echo "部署方式: GHCR 预构建镜像"
else
    echo "部署方式: 本机源码构建"
fi
echo "数据库类型: $DB_TYPE_VALUE"
echo "访问地址: http://localhost:$APP_PORT_VALUE"
echo "初始管理员: $ADMIN_USERNAME_VALUE"
echo ""
echo "查看状态: ${COMPOSE[*]} ${COMPOSE_FILES[*]} ps"
echo "查看日志: ${COMPOSE[*]} ${COMPOSE_FILES[*]} logs -f app"
echo "停止服务: ${COMPOSE[*]} ${COMPOSE_FILES[*]} down"
